x86_64_asm_source_files := $(shell find source/implement/x86_64 -name *.asm)
x86_64_asm_object_files := $(patsubst source/implement/x86_64/%.asm, build/x86_64/%.o, $(x86_64_asm_source_files))

$(x86_64_asm_source_files): build/x86_64/%.o : source/implement/x86_64/%.asm)
	mkdir -p $(dir $@) && \
	nasm -f elf64 $(patsubst build/x86_64/%.o, source/implement/x86_64/%.asm, $@) -o $@